### ISSUE TITLE
Upgrade to 1.3.1 break

### ISSUE THREAD

**Issue by silasrm** [ARCANEDEV/LaravelLang#15]
Hi,

I'm trying to upgrade this package to 1.3.1, but occurs this error:
`                                                                                                      
  [Symfony\Component\Debug\Exception\FatalThrowableError]                                             
  Call to undefined method Arcanedev\LaravelLang\Providers\CommandServiceProvider::registerCommand()  
`

This occurs because arcanedev/support change the Arcanedev\Support\Providers\CommandServiceProvider removing registerCommand method.

Any solution?

**Comment by arcanedev-maroc** [comment]
I'm going to fix that

**Comment by silasrm** [comment]
I'm trying to upgrade my app from 5.2 to 5.3.

**Comment by arcanedev-maroc** [comment]
I've created a PR to fix the issue.

The fixed release is going to be `1.4.0`.

Thanks 👍

**Comment by silasrm** [comment]
Thks @arcanedev-maroc :D
