### ISSUE TITLE
Class 'Arcanedev\LaravelLang\LaravelLangServiceProvider' not found Laravel 5.4.27

### ISSUE THREAD

**Issue by abdilahrf** [ARCANEDEV/LaravelLang#18]
- LaravelLang Version: 3.0
- Laravel Version: 5.4.27
- PHP Version: 7.0.15

### Description:
I install this by using composer
`composer require caouecs/laravel-lang:~3.0`
then i copy the folder language from `vendor/caouecs/laravel-lang/src/*` to `resources/lang/`
then i add this `Arcanedev\LaravelLang\LaravelLangServiceProvider::class` to `config/app` $providers
when i try to vendor publish i got this error 

```
[Symfony\Component\Debug\Exception\FatalThrowableError]             
  Class 'Arcanedev\LaravelLang\LaravelLangServiceProvider' not found
```

i try `composer dump-autoload` still the same

**Comment by arcanedev-maroc** [comment]
Have you installed this package by running `composer require arcanedev/laravel-lang` ?

> This is not **caouecs/laravel-lang** package.
