### ISSUE TITLE
Wrong command description?

### ISSUE THREAD

**Issue by LukasMa** [ARCANEDEV/LaravelLang#9]
Hi,
you package ships with two new artisan commands: "trans:check" and "trans:publish", but when running "artisan" to see all registered commands, the description of both commands is the same ("Check the missing translations."). I think "trans:publish" should be something like: "Publish the translations."

**Comment by arcanedev-maroc** [comment]
Thanks @LukasMa,

I've fixed it, see https://github.com/ARCANEDEV/LaravelLang/commit/c636f6e2cafcc8f868fce3c55edfac8f0e35e8ac.
